fc_one_hot_encoding:
  files:
    input_filename: "client1.csv"
    output_filename: "client1_ohe.csv"
    sep: ","
  mode: "predefined"
  categorical_variables:
    age: [ '20-29', '30-39', '40-49', '50-59', '60-69', '70-79' ]
    menopause: [ 'ge40', 'lt40', 'premeno' ]
    tumor-size: ['0-4', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39', '40-44', '45-49', '5-9', '50-54' ]
    inv-nodes: ['0-2', '12-14', '15-17', '24-26', '3-5', '6-8', '9-11']
    node-caps: ['no', 'yes']
    deg-malig: [1, 2, 3]
    breast: ['left', 'right']
    breast-quad: ['central', 'left_low', 'left_up', 'right_low', 'right_up']
    irradiat: ['no', 'yes']